### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by pllim** [comment]
Woohoo. I like what I see.

**Comment by pllim** [comment]
Maybe a bit nicer by setting:

* title = All pull requests require a milestone. 
* summary = Only maintainers...

**Comment by Cadair** [comment]
@pllim yeah, that's configurable. Let me change it.

**Comment by Cadair** [comment]
See the checks page now.

**Comment by pllim** [comment]
YAS! 👍

**Comment by pllim** [comment]
Sadly... the milestone check can easily be replaced by GitHub Action. `/laughcry`

**Pull request closed without merging**
